from typing import Optional
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String, Float, BigInteger
import app.db.connections as connections


class Base(DeclarativeBase):
    pass


class Comercializacao(Base):
    __tablename__ = "tb_comercializacao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    control: Mapped[Optional[str]] = mapped_column(String, name="control", nullable=True)
    produto: Mapped[Optional[str]] = mapped_column(String, name="produto", nullable=True)
    y1970: Mapped[Optional[float]] = mapped_column(Float, name="y1970", nullable=True)
    y1971: Mapped[Optional[float]] = mapped_column(Float, name="y1971", nullable=True)
    y1972: Mapped[Optional[float]] = mapped_column(Float, name="y1972", nullable=True)
    y1973: Mapped[Optional[float]] = mapped_column(Float, name="y1973", nullable=True)
    y1974: Mapped[Optional[float]] = mapped_column(Float, name="y1974", nullable=True)
    y1975: Mapped[Optional[float]] = mapped_column(Float, name="y1975", nullable=True)
    y1976: Mapped[Optional[float]] = mapped_column(Float, name="y1976", nullable=True)
    y1977: Mapped[Optional[float]] = mapped_column(Float, name="y1977", nullable=True)
    y1978: Mapped[Optional[float]] = mapped_column(Float, name="y1978", nullable=True)
    y1979: Mapped[Optional[float]] = mapped_column(Float, name="y1979", nullable=True)
    y1980: Mapped[Optional[float]] = mapped_column(Float, name="y1980", nullable=True)
    y1981: Mapped[Optional[float]] = mapped_column(Float, name="y1981", nullable=True)
    y1982: Mapped[Optional[float]] = mapped_column(Float, name="y1982", nullable=True)
    y1983: Mapped[Optional[float]] = mapped_column(Float, name="y1983", nullable=True)
    y1984: Mapped[Optional[float]] = mapped_column(Float, name="y1984", nullable=True)
    y1985: Mapped[Optional[float]] = mapped_column(Float, name="y1985", nullable=True)
    y1986: Mapped[Optional[float]] = mapped_column(Float, name="y1986", nullable=True)
    y1987: Mapped[Optional[float]] = mapped_column(Float, name="y1987", nullable=True)
    y1988: Mapped[Optional[float]] = mapped_column(Float, name="y1988", nullable=True)
    y1989: Mapped[Optional[float]] = mapped_column(Float, name="y1989", nullable=True)
    y1990: Mapped[Optional[float]] = mapped_column(Float, name="y1990", nullable=True)
    y1991: Mapped[Optional[float]] = mapped_column(Float, name="y1991", nullable=True)
    y1992: Mapped[Optional[float]] = mapped_column(Float, name="y1992", nullable=True)
    y1993: Mapped[Optional[float]] = mapped_column(Float, name="y1993", nullable=True)
    y1994: Mapped[Optional[float]] = mapped_column(Float, name="y1994", nullable=True)
    y1995: Mapped[Optional[float]] = mapped_column(Float, name="y1995", nullable=True)
    y1996: Mapped[Optional[float]] = mapped_column(Float, name="y1996", nullable=True)
    y1997: Mapped[Optional[float]] = mapped_column(Float, name="y1997", nullable=True)
    y1998: Mapped[Optional[float]] = mapped_column(Float, name="y1998", nullable=True)
    y1999: Mapped[Optional[float]] = mapped_column(Float, name="y1999", nullable=True)
    y2000: Mapped[Optional[float]] = mapped_column(Float, name="y2000", nullable=True)
    y2001: Mapped[Optional[float]] = mapped_column(Float, name="y2001", nullable=True)
    y2002: Mapped[Optional[float]] = mapped_column(Float, name="y2002", nullable=True)
    y2003: Mapped[Optional[float]] = mapped_column(Float, name="y2003", nullable=True)
    y2004: Mapped[Optional[float]] = mapped_column(Float, name="y2004", nullable=True)
    y2005: Mapped[Optional[float]] = mapped_column(Float, name="y2005", nullable=True)
    y2006: Mapped[Optional[float]] = mapped_column(Float, name="y2006", nullable=True)
    y2007: Mapped[Optional[float]] = mapped_column(Float, name="y2007", nullable=True)
    y2008: Mapped[Optional[float]] = mapped_column(Float, name="y2008", nullable=True)
    y2009: Mapped[Optional[float]] = mapped_column(Float, name="y2009", nullable=True)
    y2010: Mapped[Optional[float]] = mapped_column(Float, name="y2010", nullable=True)
    y2011: Mapped[Optional[float]] = mapped_column(Float, name="y2011", nullable=True)
    y2012: Mapped[Optional[float]] = mapped_column(Float, name="y2012", nullable=True)
    y2013: Mapped[Optional[float]] = mapped_column(Float, name="y2013", nullable=True)
    y2014: Mapped[Optional[float]] = mapped_column(Float, name="y2014", nullable=True)
    y2015: Mapped[Optional[float]] = mapped_column(Float, name="y2015", nullable=True)
    y2016: Mapped[Optional[float]] = mapped_column(Float, name="y2016", nullable=True)
    y2017: Mapped[Optional[float]] = mapped_column(Float, name="y2017", nullable=True)
    y2018: Mapped[Optional[float]] = mapped_column(Float, name="y2018", nullable=True)
    y2019: Mapped[Optional[float]] = mapped_column(Float, name="y2019", nullable=True)
    y2020: Mapped[Optional[float]] = mapped_column(Float, name="y2020", nullable=True)
    y2021: Mapped[Optional[float]] = mapped_column(Float, name="y2021", nullable=True)
    y2022: Mapped[Optional[float]] = mapped_column(Float, name="y2022", nullable=True)
    y2023: Mapped[Optional[float]] = mapped_column(Float, name="y2023", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Processamento(Base):
    __tablename__ = "tb_processamento"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    control: Mapped[Optional[str]] = mapped_column(String, name="control", nullable=True)
    cultivar: Mapped[Optional[str]] = mapped_column(String, name="cultivar", nullable=True)
    y1970: Mapped[Optional[float]] = mapped_column(Float, name="y1970", nullable=True)
    y1971: Mapped[Optional[float]] = mapped_column(Float, name="y1971", nullable=True)
    y1972: Mapped[Optional[float]] = mapped_column(Float, name="y1972", nullable=True)
    y1973: Mapped[Optional[float]] = mapped_column(Float, name="y1973", nullable=True)
    y1974: Mapped[Optional[float]] = mapped_column(Float, name="y1974", nullable=True)
    y1975: Mapped[Optional[float]] = mapped_column(Float, name="y1975", nullable=True)
    y1976: Mapped[Optional[float]] = mapped_column(Float, name="y1976", nullable=True)
    y1977: Mapped[Optional[float]] = mapped_column(Float, name="y1977", nullable=True)
    y1978: Mapped[Optional[float]] = mapped_column(Float, name="y1978", nullable=True)
    y1979: Mapped[Optional[float]] = mapped_column(Float, name="y1979", nullable=True)
    y1980: Mapped[Optional[float]] = mapped_column(Float, name="y1980", nullable=True)
    y1981: Mapped[Optional[float]] = mapped_column(Float, name="y1981", nullable=True)
    y1982: Mapped[Optional[float]] = mapped_column(Float, name="y1982", nullable=True)
    y1983: Mapped[Optional[float]] = mapped_column(Float, name="y1983", nullable=True)
    y1984: Mapped[Optional[float]] = mapped_column(Float, name="y1984", nullable=True)
    y1985: Mapped[Optional[float]] = mapped_column(Float, name="y1985", nullable=True)
    y1986: Mapped[Optional[float]] = mapped_column(Float, name="y1986", nullable=True)
    y1987: Mapped[Optional[float]] = mapped_column(Float, name="y1987", nullable=True)
    y1988: Mapped[Optional[float]] = mapped_column(Float, name="y1988", nullable=True)
    y1989: Mapped[Optional[float]] = mapped_column(Float, name="y1989", nullable=True)
    y1990: Mapped[Optional[float]] = mapped_column(Float, name="y1990", nullable=True)
    y1991: Mapped[Optional[float]] = mapped_column(Float, name="y1991", nullable=True)
    y1992: Mapped[Optional[float]] = mapped_column(Float, name="y1992", nullable=True)
    y1993: Mapped[Optional[float]] = mapped_column(Float, name="y1993", nullable=True)
    y1994: Mapped[Optional[float]] = mapped_column(Float, name="y1994", nullable=True)
    y1995: Mapped[Optional[float]] = mapped_column(Float, name="y1995", nullable=True)
    y1996: Mapped[Optional[float]] = mapped_column(Float, name="y1996", nullable=True)
    y1997: Mapped[Optional[float]] = mapped_column(Float, name="y1997", nullable=True)
    y1998: Mapped[Optional[float]] = mapped_column(Float, name="y1998", nullable=True)
    y1999: Mapped[Optional[float]] = mapped_column(Float, name="y1999", nullable=True)
    y2000: Mapped[Optional[float]] = mapped_column(Float, name="y2000", nullable=True)
    y2001: Mapped[Optional[float]] = mapped_column(Float, name="y2001", nullable=True)
    y2002: Mapped[Optional[float]] = mapped_column(Float, name="y2002", nullable=True)
    y2003: Mapped[Optional[float]] = mapped_column(Float, name="y2003", nullable=True)
    y2004: Mapped[Optional[float]] = mapped_column(Float, name="y2004", nullable=True)
    y2005: Mapped[Optional[float]] = mapped_column(Float, name="y2005", nullable=True)
    y2006: Mapped[Optional[float]] = mapped_column(Float, name="y2006", nullable=True)
    y2007: Mapped[Optional[float]] = mapped_column(Float, name="y2007", nullable=True)
    y2008: Mapped[Optional[float]] = mapped_column(Float, name="y2008", nullable=True)
    y2009: Mapped[Optional[float]] = mapped_column(Float, name="y2009", nullable=True)
    y2010: Mapped[Optional[float]] = mapped_column(Float, name="y2010", nullable=True)
    y2011: Mapped[Optional[float]] = mapped_column(Float, name="y2011", nullable=True)
    y2012: Mapped[Optional[float]] = mapped_column(Float, name="y2012", nullable=True)
    y2013: Mapped[Optional[float]] = mapped_column(Float, name="y2013", nullable=True)
    y2014: Mapped[Optional[float]] = mapped_column(Float, name="y2014", nullable=True)
    y2015: Mapped[Optional[float]] = mapped_column(Float, name="y2015", nullable=True)
    y2016: Mapped[Optional[float]] = mapped_column(Float, name="y2016", nullable=True)
    y2017: Mapped[Optional[float]] = mapped_column(Float, name="y2017", nullable=True)
    y2018: Mapped[Optional[float]] = mapped_column(Float, name="y2018", nullable=True)
    y2019: Mapped[Optional[float]] = mapped_column(Float, name="y2019", nullable=True)
    y2020: Mapped[Optional[float]] = mapped_column(Float, name="y2020", nullable=True)
    y2021: Mapped[Optional[float]] = mapped_column(Float, name="y2021", nullable=True)
    y2022: Mapped[Optional[float]] = mapped_column(Float, name="y2022", nullable=True)
    y2023: Mapped[Optional[float]] = mapped_column(Float, name="y2023", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Producao(Base):
    __tablename__ = "tb_producao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    control: Mapped[Optional[str]] = mapped_column(String, name="control", nullable=True)
    produto: Mapped[Optional[str]] = mapped_column(String, name="produto", nullable=True)
    y1970: Mapped[Optional[float]] = mapped_column(Float, name="y1970", nullable=True)
    y1971: Mapped[Optional[float]] = mapped_column(Float, name="y1971", nullable=True)
    y1972: Mapped[Optional[float]] = mapped_column(Float, name="y1972", nullable=True)
    y1973: Mapped[Optional[float]] = mapped_column(Float, name="y1973", nullable=True)
    y1974: Mapped[Optional[float]] = mapped_column(Float, name="y1974", nullable=True)
    y1975: Mapped[Optional[float]] = mapped_column(Float, name="y1975", nullable=True)
    y1976: Mapped[Optional[float]] = mapped_column(Float, name="y1976", nullable=True)
    y1977: Mapped[Optional[float]] = mapped_column(Float, name="y1977", nullable=True)
    y1978: Mapped[Optional[float]] = mapped_column(Float, name="y1978", nullable=True)
    y1979: Mapped[Optional[float]] = mapped_column(Float, name="y1979", nullable=True)
    y1980: Mapped[Optional[float]] = mapped_column(Float, name="y1980", nullable=True)
    y1981: Mapped[Optional[float]] = mapped_column(Float, name="y1981", nullable=True)
    y1982: Mapped[Optional[float]] = mapped_column(Float, name="y1982", nullable=True)
    y1983: Mapped[Optional[float]] = mapped_column(Float, name="y1983", nullable=True)
    y1984: Mapped[Optional[float]] = mapped_column(Float, name="y1984", nullable=True)
    y1985: Mapped[Optional[float]] = mapped_column(Float, name="y1985", nullable=True)
    y1986: Mapped[Optional[float]] = mapped_column(Float, name="y1986", nullable=True)
    y1987: Mapped[Optional[float]] = mapped_column(Float, name="y1987", nullable=True)
    y1988: Mapped[Optional[float]] = mapped_column(Float, name="y1988", nullable=True)
    y1989: Mapped[Optional[float]] = mapped_column(Float, name="y1989", nullable=True)
    y1990: Mapped[Optional[float]] = mapped_column(Float, name="y1990", nullable=True)
    y1991: Mapped[Optional[float]] = mapped_column(Float, name="y1991", nullable=True)
    y1992: Mapped[Optional[float]] = mapped_column(Float, name="y1992", nullable=True)
    y1993: Mapped[Optional[float]] = mapped_column(Float, name="y1993", nullable=True)
    y1994: Mapped[Optional[float]] = mapped_column(Float, name="y1994", nullable=True)
    y1995: Mapped[Optional[float]] = mapped_column(Float, name="y1995", nullable=True)
    y1996: Mapped[Optional[float]] = mapped_column(Float, name="y1996", nullable=True)
    y1997: Mapped[Optional[float]] = mapped_column(Float, name="y1997", nullable=True)
    y1998: Mapped[Optional[float]] = mapped_column(Float, name="y1998", nullable=True)
    y1999: Mapped[Optional[float]] = mapped_column(Float, name="y1999", nullable=True)
    y2000: Mapped[Optional[float]] = mapped_column(Float, name="y2000", nullable=True)
    y2001: Mapped[Optional[float]] = mapped_column(Float, name="y2001", nullable=True)
    y2002: Mapped[Optional[float]] = mapped_column(Float, name="y2002", nullable=True)
    y2003: Mapped[Optional[float]] = mapped_column(Float, name="y2003", nullable=True)
    y2004: Mapped[Optional[float]] = mapped_column(Float, name="y2004", nullable=True)
    y2005: Mapped[Optional[float]] = mapped_column(Float, name="y2005", nullable=True)
    y2006: Mapped[Optional[float]] = mapped_column(Float, name="y2006", nullable=True)
    y2007: Mapped[Optional[float]] = mapped_column(Float, name="y2007", nullable=True)
    y2008: Mapped[Optional[float]] = mapped_column(Float, name="y2008", nullable=True)
    y2009: Mapped[Optional[float]] = mapped_column(Float, name="y2009", nullable=True)
    y2010: Mapped[Optional[float]] = mapped_column(Float, name="y2010", nullable=True)
    y2011: Mapped[Optional[float]] = mapped_column(Float, name="y2011", nullable=True)
    y2012: Mapped[Optional[float]] = mapped_column(Float, name="y2012", nullable=True)
    y2013: Mapped[Optional[float]] = mapped_column(Float, name="y2013", nullable=True)
    y2014: Mapped[Optional[float]] = mapped_column(Float, name="y2014", nullable=True)
    y2015: Mapped[Optional[float]] = mapped_column(Float, name="y2015", nullable=True)
    y2016: Mapped[Optional[float]] = mapped_column(Float, name="y2016", nullable=True)
    y2017: Mapped[Optional[float]] = mapped_column(Float, name="y2017", nullable=True)
    y2018: Mapped[Optional[float]] = mapped_column(Float, name="y2018", nullable=True)
    y2019: Mapped[Optional[float]] = mapped_column(Float, name="y2019", nullable=True)
    y2020: Mapped[Optional[float]] = mapped_column(Float, name="y2020", nullable=True)
    y2021: Mapped[Optional[float]] = mapped_column(Float, name="y2021", nullable=True)
    y2022: Mapped[Optional[float]] = mapped_column(Float, name="y2022", nullable=True)
    y2023: Mapped[Optional[float]] = mapped_column(Float, name="y2023", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Importacao(Base):
    __tablename__ = "tb_importacao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    pais: Mapped[Optional[str]] = mapped_column(String, name="pais", nullable=True)

    # Years 1970-2024, both KG and USD
    y1970_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1970_kg", nullable=True)
    y1970_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1970_usd", nullable=True)
    y1971_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1971_kg", nullable=True)
    y1971_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1971_usd", nullable=True)
    y1972_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1972_kg", nullable=True)
    y1972_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1972_usd", nullable=True)
    y1973_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1973_kg", nullable=True)
    y1973_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1973_usd", nullable=True)
    y1974_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1974_kg", nullable=True)
    y1974_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1974_usd", nullable=True)
    y1975_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1975_kg", nullable=True)
    y1975_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1975_usd", nullable=True)
    y1976_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1976_kg", nullable=True)
    y1976_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1976_usd", nullable=True)
    y1977_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1977_kg", nullable=True)
    y1977_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1977_usd", nullable=True)
    y1978_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1978_kg", nullable=True)
    y1978_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1978_usd", nullable=True)
    y1979_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1979_kg", nullable=True)
    y1979_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1979_usd", nullable=True)
    y1980_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1980_kg", nullable=True)
    y1980_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1980_usd", nullable=True)
    y1981_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1981_kg", nullable=True)
    y1981_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1981_usd", nullable=True)
    y1982_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1982_kg", nullable=True)
    y1982_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1982_usd", nullable=True)
    y1983_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1983_kg", nullable=True)
    y1983_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1983_usd", nullable=True)
    y1984_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1984_kg", nullable=True)
    y1984_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1984_usd", nullable=True)
    y1985_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1985_kg", nullable=True)
    y1985_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1985_usd", nullable=True)
    y1986_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1986_kg", nullable=True)
    y1986_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1986_usd", nullable=True)
    y1987_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1987_kg", nullable=True)
    y1987_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1987_usd", nullable=True)
    y1988_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1988_kg", nullable=True)
    y1988_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1988_usd", nullable=True)
    y1989_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1989_kg", nullable=True)
    y1989_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1989_usd", nullable=True)
    y1990_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1990_kg", nullable=True)
    y1990_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1990_usd", nullable=True)
    y1991_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1991_kg", nullable=True)
    y1991_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1991_usd", nullable=True)
    y1992_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1992_kg", nullable=True)
    y1992_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1992_usd", nullable=True)
    y1993_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1993_kg", nullable=True)
    y1993_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1993_usd", nullable=True)
    y1994_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1994_kg", nullable=True)
    y1994_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1994_usd", nullable=True)
    y1995_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1995_kg", nullable=True)
    y1995_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1995_usd", nullable=True)
    y1996_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1996_kg", nullable=True)
    y1996_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1996_usd", nullable=True)
    y1997_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1997_kg", nullable=True)
    y1997_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1997_usd", nullable=True)
    y1998_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1998_kg", nullable=True)
    y1998_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1998_usd", nullable=True)
    y1999_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1999_kg", nullable=True)
    y1999_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1999_usd", nullable=True)
    y2000_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2000_kg", nullable=True)
    y2000_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2000_usd", nullable=True)
    y2001_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2001_kg", nullable=True)
    y2001_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2001_usd", nullable=True)
    y2002_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2002_kg", nullable=True)
    y2002_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2002_usd", nullable=True)
    y2003_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2003_kg", nullable=True)
    y2003_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2003_usd", nullable=True)
    y2004_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2004_kg", nullable=True)
    y2004_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2004_usd", nullable=True)
    y2005_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2005_kg", nullable=True)
    y2005_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2005_usd", nullable=True)
    y2006_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2006_kg", nullable=True)
    y2006_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2006_usd", nullable=True)
    y2007_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2007_kg", nullable=True)
    y2007_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2007_usd", nullable=True)
    y2008_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2008_kg", nullable=True)
    y2008_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2008_usd", nullable=True)
    y2009_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2009_kg", nullable=True)
    y2009_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2009_usd", nullable=True)
    y2010_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2010_kg", nullable=True)
    y2010_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2010_usd", nullable=True)
    y2011_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2011_kg", nullable=True)
    y2011_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2011_usd", nullable=True)
    y2012_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2012_kg", nullable=True)
    y2012_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2012_usd", nullable=True)
    y2013_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2013_kg", nullable=True)
    y2013_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2013_usd", nullable=True)
    y2014_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2014_kg", nullable=True)
    y2014_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2014_usd", nullable=True)
    y2015_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2015_kg", nullable=True)
    y2015_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2015_usd", nullable=True)
    y2016_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2016_kg", nullable=True)
    y2016_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2016_usd", nullable=True)
    y2017_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2017_kg", nullable=True)
    y2017_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2017_usd", nullable=True)
    y2018_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2018_kg", nullable=True)
    y2018_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2018_usd", nullable=True)
    y2019_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2019_kg", nullable=True)
    y2019_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2019_usd", nullable=True)
    y2020_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2020_kg", nullable=True)
    y2020_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2020_usd", nullable=True)
    y2021_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2021_kg", nullable=True)
    y2021_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2021_usd", nullable=True)
    y2022_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2022_kg", nullable=True)
    y2022_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2022_usd", nullable=True)
    y2023_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2023_kg", nullable=True)
    y2023_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2023_usd", nullable=True)
    y2024_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2024_kg", nullable=True)
    y2024_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2024_usd", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Exportacao(Base):
    __tablename__ = "tb_exportacao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    pais: Mapped[Optional[str]] = mapped_column(String, name="pais", nullable=True)

    # Years 1970-2024, both KG and USD
    y1970_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1970_kg", nullable=True)
    y1970_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1970_usd", nullable=True)
    y1971_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1971_kg", nullable=True)
    y1971_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1971_usd", nullable=True)
    y1972_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1972_kg", nullable=True)
    y1972_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1972_usd", nullable=True)
    y1973_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1973_kg", nullable=True)
    y1973_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1973_usd", nullable=True)
    y1974_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1974_kg", nullable=True)
    y1974_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1974_usd", nullable=True)
    y1975_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1975_kg", nullable=True)
    y1975_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1975_usd", nullable=True)
    y1976_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1976_kg", nullable=True)
    y1976_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1976_usd", nullable=True)
    y1977_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1977_kg", nullable=True)
    y1977_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1977_usd", nullable=True)
    y1978_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1978_kg", nullable=True)
    y1978_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1978_usd", nullable=True)
    y1979_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1979_kg", nullable=True)
    y1979_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1979_usd", nullable=True)
    y1980_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1980_kg", nullable=True)
    y1980_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1980_usd", nullable=True)
    y1981_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1981_kg", nullable=True)
    y1981_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1981_usd", nullable=True)
    y1982_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1982_kg", nullable=True)
    y1982_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1982_usd", nullable=True)
    y1983_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1983_kg", nullable=True)
    y1983_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1983_usd", nullable=True)
    y1984_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1984_kg", nullable=True)
    y1984_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1984_usd", nullable=True)
    y1985_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1985_kg", nullable=True)
    y1985_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1985_usd", nullable=True)
    y1986_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1986_kg", nullable=True)
    y1986_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1986_usd", nullable=True)
    y1987_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1987_kg", nullable=True)
    y1987_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1987_usd", nullable=True)
    y1988_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1988_kg", nullable=True)
    y1988_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1988_usd", nullable=True)
    y1989_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1989_kg", nullable=True)
    y1989_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1989_usd", nullable=True)
    y1990_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1990_kg", nullable=True)
    y1990_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1990_usd", nullable=True)
    y1991_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1991_kg", nullable=True)
    y1991_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1991_usd", nullable=True)
    y1992_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1992_kg", nullable=True)
    y1992_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1992_usd", nullable=True)
    y1993_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1993_kg", nullable=True)
    y1993_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1993_usd", nullable=True)
    y1994_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1994_kg", nullable=True)
    y1994_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1994_usd", nullable=True)
    y1995_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1995_kg", nullable=True)
    y1995_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1995_usd", nullable=True)
    y1996_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1996_kg", nullable=True)
    y1996_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1996_usd", nullable=True)
    y1997_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1997_kg", nullable=True)
    y1997_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1997_usd", nullable=True)
    y1998_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1998_kg", nullable=True)
    y1998_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1998_usd", nullable=True)
    y1999_kg: Mapped[Optional[float]] = mapped_column(Float, name="y1999_kg", nullable=True)
    y1999_usd: Mapped[Optional[float]] = mapped_column(Float, name="y1999_usd", nullable=True)
    y2000_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2000_kg", nullable=True)
    y2000_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2000_usd", nullable=True)
    y2001_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2001_kg", nullable=True)
    y2001_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2001_usd", nullable=True)
    y2002_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2002_kg", nullable=True)
    y2002_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2002_usd", nullable=True)
    y2003_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2003_kg", nullable=True)
    y2003_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2003_usd", nullable=True)
    y2004_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2004_kg", nullable=True)
    y2004_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2004_usd", nullable=True)
    y2005_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2005_kg", nullable=True)
    y2005_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2005_usd", nullable=True)
    y2006_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2006_kg", nullable=True)
    y2006_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2006_usd", nullable=True)
    y2007_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2007_kg", nullable=True)
    y2007_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2007_usd", nullable=True)
    y2008_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2008_kg", nullable=True)
    y2008_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2008_usd", nullable=True)
    y2009_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2009_kg", nullable=True)
    y2009_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2009_usd", nullable=True)
    y2010_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2010_kg", nullable=True)
    y2010_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2010_usd", nullable=True)
    y2011_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2011_kg", nullable=True)
    y2011_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2011_usd", nullable=True)
    y2012_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2012_kg", nullable=True)
    y2012_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2012_usd", nullable=True)
    y2013_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2013_kg", nullable=True)
    y2013_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2013_usd", nullable=True)
    y2014_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2014_kg", nullable=True)
    y2014_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2014_usd", nullable=True)
    y2015_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2015_kg", nullable=True)
    y2015_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2015_usd", nullable=True)
    y2016_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2016_kg", nullable=True)
    y2016_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2016_usd", nullable=True)
    y2017_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2017_kg", nullable=True)
    y2017_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2017_usd", nullable=True)
    y2018_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2018_kg", nullable=True)
    y2018_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2018_usd", nullable=True)
    y2019_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2019_kg", nullable=True)
    y2019_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2019_usd", nullable=True)
    y2020_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2020_kg", nullable=True)
    y2020_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2020_usd", nullable=True)
    y2021_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2021_kg", nullable=True)
    y2021_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2021_usd", nullable=True)
    y2022_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2022_kg", nullable=True)
    y2022_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2022_usd", nullable=True)
    y2023_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2023_kg", nullable=True)
    y2023_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2023_usd", nullable=True)
    y2024_kg: Mapped[Optional[float]] = mapped_column(Float, name="y2024_kg", nullable=True)
    y2024_usd: Mapped[Optional[float]] = mapped_column(Float, name="y2024_usd", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


def create_tables():
    """Create all tables in the database."""
    engine = connections.get_engine()
    Base.metadata.create_all(engine)
