from typing import Optional
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String, Float, BigInteger
import app.db.connections as connections


class Base(DeclarativeBase):
    pass


class Comercializacao(Base):
    __tablename__ = "stg_comercializacao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    control: Mapped[Optional[str]] = mapped_column(String, name="control", nullable=True)
    produto: Mapped[Optional[str]] = mapped_column(String, name="produto", nullable=True)
    y1970: Mapped[Optional[float]] = mapped_column(Float, name="1970", nullable=True)
    y1971: Mapped[Optional[float]] = mapped_column(Float, name="1971", nullable=True)
    y1972: Mapped[Optional[float]] = mapped_column(Float, name="1972", nullable=True)
    y1973: Mapped[Optional[float]] = mapped_column(Float, name="1973", nullable=True)
    y1974: Mapped[Optional[float]] = mapped_column(Float, name="1974", nullable=True)
    y1975: Mapped[Optional[float]] = mapped_column(Float, name="1975", nullable=True)
    y1976: Mapped[Optional[float]] = mapped_column(Float, name="1976", nullable=True)
    y1977: Mapped[Optional[float]] = mapped_column(Float, name="1977", nullable=True)
    y1978: Mapped[Optional[float]] = mapped_column(Float, name="1978", nullable=True)
    y1979: Mapped[Optional[float]] = mapped_column(Float, name="1979", nullable=True)
    y1980: Mapped[Optional[float]] = mapped_column(Float, name="1980", nullable=True)
    y1981: Mapped[Optional[float]] = mapped_column(Float, name="1981", nullable=True)
    y1982: Mapped[Optional[float]] = mapped_column(Float, name="1982", nullable=True)
    y1983: Mapped[Optional[float]] = mapped_column(Float, name="1983", nullable=True)
    y1984: Mapped[Optional[float]] = mapped_column(Float, name="1984", nullable=True)
    y1985: Mapped[Optional[float]] = mapped_column(Float, name="1985", nullable=True)
    y1986: Mapped[Optional[float]] = mapped_column(Float, name="1986", nullable=True)
    y1987: Mapped[Optional[float]] = mapped_column(Float, name="1987", nullable=True)
    y1988: Mapped[Optional[float]] = mapped_column(Float, name="1988", nullable=True)
    y1989: Mapped[Optional[float]] = mapped_column(Float, name="1989", nullable=True)
    y1990: Mapped[Optional[float]] = mapped_column(Float, name="1990", nullable=True)
    y1991: Mapped[Optional[float]] = mapped_column(Float, name="1991", nullable=True)
    y1992: Mapped[Optional[float]] = mapped_column(Float, name="1992", nullable=True)
    y1993: Mapped[Optional[float]] = mapped_column(Float, name="1993", nullable=True)
    y1994: Mapped[Optional[float]] = mapped_column(Float, name="1994", nullable=True)
    y1995: Mapped[Optional[float]] = mapped_column(Float, name="1995", nullable=True)
    y1996: Mapped[Optional[float]] = mapped_column(Float, name="1996", nullable=True)
    y1997: Mapped[Optional[float]] = mapped_column(Float, name="1997", nullable=True)
    y1998: Mapped[Optional[float]] = mapped_column(Float, name="1998", nullable=True)
    y1999: Mapped[Optional[float]] = mapped_column(Float, name="1999", nullable=True)
    y2000: Mapped[Optional[float]] = mapped_column(Float, name="2000", nullable=True)
    y2001: Mapped[Optional[float]] = mapped_column(Float, name="2001", nullable=True)
    y2002: Mapped[Optional[float]] = mapped_column(Float, name="2002", nullable=True)
    y2003: Mapped[Optional[float]] = mapped_column(Float, name="2003", nullable=True)
    y2004: Mapped[Optional[float]] = mapped_column(Float, name="2004", nullable=True)
    y2005: Mapped[Optional[float]] = mapped_column(Float, name="2005", nullable=True)
    y2006: Mapped[Optional[float]] = mapped_column(Float, name="2006", nullable=True)
    y2007: Mapped[Optional[float]] = mapped_column(Float, name="2007", nullable=True)
    y2008: Mapped[Optional[float]] = mapped_column(Float, name="2008", nullable=True)
    y2009: Mapped[Optional[float]] = mapped_column(Float, name="2009", nullable=True)
    y2010: Mapped[Optional[float]] = mapped_column(Float, name="2010", nullable=True)
    y2011: Mapped[Optional[float]] = mapped_column(Float, name="2011", nullable=True)
    y2012: Mapped[Optional[float]] = mapped_column(Float, name="2012", nullable=True)
    y2013: Mapped[Optional[float]] = mapped_column(Float, name="2013", nullable=True)
    y2014: Mapped[Optional[float]] = mapped_column(Float, name="2014", nullable=True)
    y2015: Mapped[Optional[float]] = mapped_column(Float, name="2015", nullable=True)
    y2016: Mapped[Optional[float]] = mapped_column(Float, name="2016", nullable=True)
    y2017: Mapped[Optional[float]] = mapped_column(Float, name="2017", nullable=True)
    y2018: Mapped[Optional[float]] = mapped_column(Float, name="2018", nullable=True)
    y2019: Mapped[Optional[float]] = mapped_column(Float, name="2019", nullable=True)
    y2020: Mapped[Optional[float]] = mapped_column(Float, name="2020", nullable=True)
    y2021: Mapped[Optional[float]] = mapped_column(Float, name="2021", nullable=True)
    y2022: Mapped[Optional[float]] = mapped_column(Float, name="2022", nullable=True)
    y2023: Mapped[Optional[float]] = mapped_column(Float, name="2023", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Processamento(Base):
    __tablename__ = "stg_processamento"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    control: Mapped[Optional[str]] = mapped_column(String, name="control", nullable=True)
    cultivar: Mapped[Optional[str]] = mapped_column(String, name="cultivar", nullable=True)
    y1970: Mapped[Optional[float]] = mapped_column(Float, name="1970", nullable=True)
    y1971: Mapped[Optional[float]] = mapped_column(Float, name="1971", nullable=True)
    y1972: Mapped[Optional[float]] = mapped_column(Float, name="1972", nullable=True)
    y1973: Mapped[Optional[float]] = mapped_column(Float, name="1973", nullable=True)
    y1974: Mapped[Optional[float]] = mapped_column(Float, name="1974", nullable=True)
    y1975: Mapped[Optional[float]] = mapped_column(Float, name="1975", nullable=True)
    y1976: Mapped[Optional[float]] = mapped_column(Float, name="1976", nullable=True)
    y1977: Mapped[Optional[float]] = mapped_column(Float, name="1977", nullable=True)
    y1978: Mapped[Optional[float]] = mapped_column(Float, name="1978", nullable=True)
    y1979: Mapped[Optional[float]] = mapped_column(Float, name="1979", nullable=True)
    y1980: Mapped[Optional[float]] = mapped_column(Float, name="1980", nullable=True)
    y1981: Mapped[Optional[float]] = mapped_column(Float, name="1981", nullable=True)
    y1982: Mapped[Optional[float]] = mapped_column(Float, name="1982", nullable=True)
    y1983: Mapped[Optional[float]] = mapped_column(Float, name="1983", nullable=True)
    y1984: Mapped[Optional[float]] = mapped_column(Float, name="1984", nullable=True)
    y1985: Mapped[Optional[float]] = mapped_column(Float, name="1985", nullable=True)
    y1986: Mapped[Optional[float]] = mapped_column(Float, name="1986", nullable=True)
    y1987: Mapped[Optional[float]] = mapped_column(Float, name="1987", nullable=True)
    y1988: Mapped[Optional[float]] = mapped_column(Float, name="1988", nullable=True)
    y1989: Mapped[Optional[float]] = mapped_column(Float, name="1989", nullable=True)
    y1990: Mapped[Optional[float]] = mapped_column(Float, name="1990", nullable=True)
    y1991: Mapped[Optional[float]] = mapped_column(Float, name="1991", nullable=True)
    y1992: Mapped[Optional[float]] = mapped_column(Float, name="1992", nullable=True)
    y1993: Mapped[Optional[float]] = mapped_column(Float, name="1993", nullable=True)
    y1994: Mapped[Optional[float]] = mapped_column(Float, name="1994", nullable=True)
    y1995: Mapped[Optional[float]] = mapped_column(Float, name="1995", nullable=True)
    y1996: Mapped[Optional[float]] = mapped_column(Float, name="1996", nullable=True)
    y1997: Mapped[Optional[float]] = mapped_column(Float, name="1997", nullable=True)
    y1998: Mapped[Optional[float]] = mapped_column(Float, name="1998", nullable=True)
    y1999: Mapped[Optional[float]] = mapped_column(Float, name="1999", nullable=True)
    y2000: Mapped[Optional[float]] = mapped_column(Float, name="2000", nullable=True)
    y2001: Mapped[Optional[float]] = mapped_column(Float, name="2001", nullable=True)
    y2002: Mapped[Optional[float]] = mapped_column(Float, name="2002", nullable=True)
    y2003: Mapped[Optional[float]] = mapped_column(Float, name="2003", nullable=True)
    y2004: Mapped[Optional[float]] = mapped_column(Float, name="2004", nullable=True)
    y2005: Mapped[Optional[float]] = mapped_column(Float, name="2005", nullable=True)
    y2006: Mapped[Optional[float]] = mapped_column(Float, name="2006", nullable=True)
    y2007: Mapped[Optional[float]] = mapped_column(Float, name="2007", nullable=True)
    y2008: Mapped[Optional[float]] = mapped_column(Float, name="2008", nullable=True)
    y2009: Mapped[Optional[float]] = mapped_column(Float, name="2009", nullable=True)
    y2010: Mapped[Optional[float]] = mapped_column(Float, name="2010", nullable=True)
    y2011: Mapped[Optional[float]] = mapped_column(Float, name="2011", nullable=True)
    y2012: Mapped[Optional[float]] = mapped_column(Float, name="2012", nullable=True)
    y2013: Mapped[Optional[float]] = mapped_column(Float, name="2013", nullable=True)
    y2014: Mapped[Optional[float]] = mapped_column(Float, name="2014", nullable=True)
    y2015: Mapped[Optional[float]] = mapped_column(Float, name="2015", nullable=True)
    y2016: Mapped[Optional[float]] = mapped_column(Float, name="2016", nullable=True)
    y2017: Mapped[Optional[float]] = mapped_column(Float, name="2017", nullable=True)
    y2018: Mapped[Optional[float]] = mapped_column(Float, name="2018", nullable=True)
    y2019: Mapped[Optional[float]] = mapped_column(Float, name="2019", nullable=True)
    y2020: Mapped[Optional[float]] = mapped_column(Float, name="2020", nullable=True)
    y2021: Mapped[Optional[float]] = mapped_column(Float, name="2021", nullable=True)
    y2022: Mapped[Optional[float]] = mapped_column(Float, name="2022", nullable=True)
    y2023: Mapped[Optional[float]] = mapped_column(Float, name="2023", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Producao(Base):
    __tablename__ = "stg_producao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    control: Mapped[Optional[str]] = mapped_column(String, name="control", nullable=True)
    produto: Mapped[Optional[str]] = mapped_column(String, name="produto", nullable=True)
    y1970: Mapped[Optional[float]] = mapped_column(Float, name="1970", nullable=True)
    y1971: Mapped[Optional[float]] = mapped_column(Float, name="1971", nullable=True)
    y1972: Mapped[Optional[float]] = mapped_column(Float, name="1972", nullable=True)
    y1973: Mapped[Optional[float]] = mapped_column(Float, name="1973", nullable=True)
    y1974: Mapped[Optional[float]] = mapped_column(Float, name="1974", nullable=True)
    y1975: Mapped[Optional[float]] = mapped_column(Float, name="1975", nullable=True)
    y1976: Mapped[Optional[float]] = mapped_column(Float, name="1976", nullable=True)
    y1977: Mapped[Optional[float]] = mapped_column(Float, name="1977", nullable=True)
    y1978: Mapped[Optional[float]] = mapped_column(Float, name="1978", nullable=True)
    y1979: Mapped[Optional[float]] = mapped_column(Float, name="1979", nullable=True)
    y1980: Mapped[Optional[float]] = mapped_column(Float, name="1980", nullable=True)
    y1981: Mapped[Optional[float]] = mapped_column(Float, name="1981", nullable=True)
    y1982: Mapped[Optional[float]] = mapped_column(Float, name="1982", nullable=True)
    y1983: Mapped[Optional[float]] = mapped_column(Float, name="1983", nullable=True)
    y1984: Mapped[Optional[float]] = mapped_column(Float, name="1984", nullable=True)
    y1985: Mapped[Optional[float]] = mapped_column(Float, name="1985", nullable=True)
    y1986: Mapped[Optional[float]] = mapped_column(Float, name="1986", nullable=True)
    y1987: Mapped[Optional[float]] = mapped_column(Float, name="1987", nullable=True)
    y1988: Mapped[Optional[float]] = mapped_column(Float, name="1988", nullable=True)
    y1989: Mapped[Optional[float]] = mapped_column(Float, name="1989", nullable=True)
    y1990: Mapped[Optional[float]] = mapped_column(Float, name="1990", nullable=True)
    y1991: Mapped[Optional[float]] = mapped_column(Float, name="1991", nullable=True)
    y1992: Mapped[Optional[float]] = mapped_column(Float, name="1992", nullable=True)
    y1993: Mapped[Optional[float]] = mapped_column(Float, name="1993", nullable=True)
    y1994: Mapped[Optional[float]] = mapped_column(Float, name="1994", nullable=True)
    y1995: Mapped[Optional[float]] = mapped_column(Float, name="1995", nullable=True)
    y1996: Mapped[Optional[float]] = mapped_column(Float, name="1996", nullable=True)
    y1997: Mapped[Optional[float]] = mapped_column(Float, name="1997", nullable=True)
    y1998: Mapped[Optional[float]] = mapped_column(Float, name="1998", nullable=True)
    y1999: Mapped[Optional[float]] = mapped_column(Float, name="1999", nullable=True)
    y2000: Mapped[Optional[float]] = mapped_column(Float, name="2000", nullable=True)
    y2001: Mapped[Optional[float]] = mapped_column(Float, name="2001", nullable=True)
    y2002: Mapped[Optional[float]] = mapped_column(Float, name="2002", nullable=True)
    y2003: Mapped[Optional[float]] = mapped_column(Float, name="2003", nullable=True)
    y2004: Mapped[Optional[float]] = mapped_column(Float, name="2004", nullable=True)
    y2005: Mapped[Optional[float]] = mapped_column(Float, name="2005", nullable=True)
    y2006: Mapped[Optional[float]] = mapped_column(Float, name="2006", nullable=True)
    y2007: Mapped[Optional[float]] = mapped_column(Float, name="2007", nullable=True)
    y2008: Mapped[Optional[float]] = mapped_column(Float, name="2008", nullable=True)
    y2009: Mapped[Optional[float]] = mapped_column(Float, name="2009", nullable=True)
    y2010: Mapped[Optional[float]] = mapped_column(Float, name="2010", nullable=True)
    y2011: Mapped[Optional[float]] = mapped_column(Float, name="2011", nullable=True)
    y2012: Mapped[Optional[float]] = mapped_column(Float, name="2012", nullable=True)
    y2013: Mapped[Optional[float]] = mapped_column(Float, name="2013", nullable=True)
    y2014: Mapped[Optional[float]] = mapped_column(Float, name="2014", nullable=True)
    y2015: Mapped[Optional[float]] = mapped_column(Float, name="2015", nullable=True)
    y2016: Mapped[Optional[float]] = mapped_column(Float, name="2016", nullable=True)
    y2017: Mapped[Optional[float]] = mapped_column(Float, name="2017", nullable=True)
    y2018: Mapped[Optional[float]] = mapped_column(Float, name="2018", nullable=True)
    y2019: Mapped[Optional[float]] = mapped_column(Float, name="2019", nullable=True)
    y2020: Mapped[Optional[float]] = mapped_column(Float, name="2020", nullable=True)
    y2021: Mapped[Optional[float]] = mapped_column(Float, name="2021", nullable=True)
    y2022: Mapped[Optional[float]] = mapped_column(Float, name="2022", nullable=True)
    y2023: Mapped[Optional[float]] = mapped_column(Float, name="2023", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Importacao(Base):
    __tablename__ = "stg_importacao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    pais: Mapped[Optional[str]] = mapped_column(String, name="pais", nullable=True)

    # Years 1970-2024, both KG and USD
    y1970_kg: Mapped[Optional[float]] = mapped_column(Float, name="1970_KG", nullable=True)
    y1970_usd: Mapped[Optional[float]] = mapped_column(Float, name="1970_USD", nullable=True)
    y1971_kg: Mapped[Optional[float]] = mapped_column(Float, name="1971_KG", nullable=True)
    y1971_usd: Mapped[Optional[float]] = mapped_column(Float, name="1971_USD", nullable=True)
    y1972_kg: Mapped[Optional[float]] = mapped_column(Float, name="1972_KG", nullable=True)
    y1972_usd: Mapped[Optional[float]] = mapped_column(Float, name="1972_USD", nullable=True)
    y1973_kg: Mapped[Optional[float]] = mapped_column(Float, name="1973_KG", nullable=True)
    y1973_usd: Mapped[Optional[float]] = mapped_column(Float, name="1973_USD", nullable=True)
    y1974_kg: Mapped[Optional[float]] = mapped_column(Float, name="1974_KG", nullable=True)
    y1974_usd: Mapped[Optional[float]] = mapped_column(Float, name="1974_USD", nullable=True)
    y1975_kg: Mapped[Optional[float]] = mapped_column(Float, name="1975_KG", nullable=True)
    y1975_usd: Mapped[Optional[float]] = mapped_column(Float, name="1975_USD", nullable=True)
    y1976_kg: Mapped[Optional[float]] = mapped_column(Float, name="1976_KG", nullable=True)
    y1976_usd: Mapped[Optional[float]] = mapped_column(Float, name="1976_USD", nullable=True)
    y1977_kg: Mapped[Optional[float]] = mapped_column(Float, name="1977_KG", nullable=True)
    y1977_usd: Mapped[Optional[float]] = mapped_column(Float, name="1977_USD", nullable=True)
    y1978_kg: Mapped[Optional[float]] = mapped_column(Float, name="1978_KG", nullable=True)
    y1978_usd: Mapped[Optional[float]] = mapped_column(Float, name="1978_USD", nullable=True)
    y1979_kg: Mapped[Optional[float]] = mapped_column(Float, name="1979_KG", nullable=True)
    y1979_usd: Mapped[Optional[float]] = mapped_column(Float, name="1979_USD", nullable=True)
    y1980_kg: Mapped[Optional[float]] = mapped_column(Float, name="1980_KG", nullable=True)
    y1980_usd: Mapped[Optional[float]] = mapped_column(Float, name="1980_USD", nullable=True)
    y1981_kg: Mapped[Optional[float]] = mapped_column(Float, name="1981_KG", nullable=True)
    y1981_usd: Mapped[Optional[float]] = mapped_column(Float, name="1981_USD", nullable=True)
    y1982_kg: Mapped[Optional[float]] = mapped_column(Float, name="1982_KG", nullable=True)
    y1982_usd: Mapped[Optional[float]] = mapped_column(Float, name="1982_USD", nullable=True)
    y1983_kg: Mapped[Optional[float]] = mapped_column(Float, name="1983_KG", nullable=True)
    y1983_usd: Mapped[Optional[float]] = mapped_column(Float, name="1983_USD", nullable=True)
    y1984_kg: Mapped[Optional[float]] = mapped_column(Float, name="1984_KG", nullable=True)
    y1984_usd: Mapped[Optional[float]] = mapped_column(Float, name="1984_USD", nullable=True)
    y1985_kg: Mapped[Optional[float]] = mapped_column(Float, name="1985_KG", nullable=True)
    y1985_usd: Mapped[Optional[float]] = mapped_column(Float, name="1985_USD", nullable=True)
    y1986_kg: Mapped[Optional[float]] = mapped_column(Float, name="1986_KG", nullable=True)
    y1986_usd: Mapped[Optional[float]] = mapped_column(Float, name="1986_USD", nullable=True)
    y1987_kg: Mapped[Optional[float]] = mapped_column(Float, name="1987_KG", nullable=True)
    y1987_usd: Mapped[Optional[float]] = mapped_column(Float, name="1987_USD", nullable=True)
    y1988_kg: Mapped[Optional[float]] = mapped_column(Float, name="1988_KG", nullable=True)
    y1988_usd: Mapped[Optional[float]] = mapped_column(Float, name="1988_USD", nullable=True)
    y1989_kg: Mapped[Optional[float]] = mapped_column(Float, name="1989_KG", nullable=True)
    y1989_usd: Mapped[Optional[float]] = mapped_column(Float, name="1989_USD", nullable=True)
    y1990_kg: Mapped[Optional[float]] = mapped_column(Float, name="1990_KG", nullable=True)
    y1990_usd: Mapped[Optional[float]] = mapped_column(Float, name="1990_USD", nullable=True)
    y1991_kg: Mapped[Optional[float]] = mapped_column(Float, name="1991_KG", nullable=True)
    y1991_usd: Mapped[Optional[float]] = mapped_column(Float, name="1991_USD", nullable=True)
    y1992_kg: Mapped[Optional[float]] = mapped_column(Float, name="1992_KG", nullable=True)
    y1992_usd: Mapped[Optional[float]] = mapped_column(Float, name="1992_USD", nullable=True)
    y1993_kg: Mapped[Optional[float]] = mapped_column(Float, name="1993_KG", nullable=True)
    y1993_usd: Mapped[Optional[float]] = mapped_column(Float, name="1993_USD", nullable=True)
    y1994_kg: Mapped[Optional[float]] = mapped_column(Float, name="1994_KG", nullable=True)
    y1994_usd: Mapped[Optional[float]] = mapped_column(Float, name="1994_USD", nullable=True)
    y1995_kg: Mapped[Optional[float]] = mapped_column(Float, name="1995_KG", nullable=True)
    y1995_usd: Mapped[Optional[float]] = mapped_column(Float, name="1995_USD", nullable=True)
    y1996_kg: Mapped[Optional[float]] = mapped_column(Float, name="1996_KG", nullable=True)
    y1996_usd: Mapped[Optional[float]] = mapped_column(Float, name="1996_USD", nullable=True)
    y1997_kg: Mapped[Optional[float]] = mapped_column(Float, name="1997_KG", nullable=True)
    y1997_usd: Mapped[Optional[float]] = mapped_column(Float, name="1997_USD", nullable=True)
    y1998_kg: Mapped[Optional[float]] = mapped_column(Float, name="1998_KG", nullable=True)
    y1998_usd: Mapped[Optional[float]] = mapped_column(Float, name="1998_USD", nullable=True)
    y1999_kg: Mapped[Optional[float]] = mapped_column(Float, name="1999_KG", nullable=True)
    y1999_usd: Mapped[Optional[float]] = mapped_column(Float, name="1999_USD", nullable=True)
    y2000_kg: Mapped[Optional[float]] = mapped_column(Float, name="2000_KG", nullable=True)
    y2000_usd: Mapped[Optional[float]] = mapped_column(Float, name="2000_USD", nullable=True)
    y2001_kg: Mapped[Optional[float]] = mapped_column(Float, name="2001_KG", nullable=True)
    y2001_usd: Mapped[Optional[float]] = mapped_column(Float, name="2001_USD", nullable=True)
    y2002_kg: Mapped[Optional[float]] = mapped_column(Float, name="2002_KG", nullable=True)
    y2002_usd: Mapped[Optional[float]] = mapped_column(Float, name="2002_USD", nullable=True)
    y2003_kg: Mapped[Optional[float]] = mapped_column(Float, name="2003_KG", nullable=True)
    y2003_usd: Mapped[Optional[float]] = mapped_column(Float, name="2003_USD", nullable=True)
    y2004_kg: Mapped[Optional[float]] = mapped_column(Float, name="2004_KG", nullable=True)
    y2004_usd: Mapped[Optional[float]] = mapped_column(Float, name="2004_USD", nullable=True)
    y2005_kg: Mapped[Optional[float]] = mapped_column(Float, name="2005_KG", nullable=True)
    y2005_usd: Mapped[Optional[float]] = mapped_column(Float, name="2005_USD", nullable=True)
    y2006_kg: Mapped[Optional[float]] = mapped_column(Float, name="2006_KG", nullable=True)
    y2006_usd: Mapped[Optional[float]] = mapped_column(Float, name="2006_USD", nullable=True)
    y2007_kg: Mapped[Optional[float]] = mapped_column(Float, name="2007_KG", nullable=True)
    y2007_usd: Mapped[Optional[float]] = mapped_column(Float, name="2007_USD", nullable=True)
    y2008_kg: Mapped[Optional[float]] = mapped_column(Float, name="2008_KG", nullable=True)
    y2008_usd: Mapped[Optional[float]] = mapped_column(Float, name="2008_USD", nullable=True)
    y2009_kg: Mapped[Optional[float]] = mapped_column(Float, name="2009_KG", nullable=True)
    y2009_usd: Mapped[Optional[float]] = mapped_column(Float, name="2009_USD", nullable=True)
    y2010_kg: Mapped[Optional[float]] = mapped_column(Float, name="2010_KG", nullable=True)
    y2010_usd: Mapped[Optional[float]] = mapped_column(Float, name="2010_USD", nullable=True)
    y2011_kg: Mapped[Optional[float]] = mapped_column(Float, name="2011_KG", nullable=True)
    y2011_usd: Mapped[Optional[float]] = mapped_column(Float, name="2011_USD", nullable=True)
    y2012_kg: Mapped[Optional[float]] = mapped_column(Float, name="2012_KG", nullable=True)
    y2012_usd: Mapped[Optional[float]] = mapped_column(Float, name="2012_USD", nullable=True)
    y2013_kg: Mapped[Optional[float]] = mapped_column(Float, name="2013_KG", nullable=True)
    y2013_usd: Mapped[Optional[float]] = mapped_column(Float, name="2013_USD", nullable=True)
    y2014_kg: Mapped[Optional[float]] = mapped_column(Float, name="2014_KG", nullable=True)
    y2014_usd: Mapped[Optional[float]] = mapped_column(Float, name="2014_USD", nullable=True)
    y2015_kg: Mapped[Optional[float]] = mapped_column(Float, name="2015_KG", nullable=True)
    y2015_usd: Mapped[Optional[float]] = mapped_column(Float, name="2015_USD", nullable=True)
    y2016_kg: Mapped[Optional[float]] = mapped_column(Float, name="2016_KG", nullable=True)
    y2016_usd: Mapped[Optional[float]] = mapped_column(Float, name="2016_USD", nullable=True)
    y2017_kg: Mapped[Optional[float]] = mapped_column(Float, name="2017_KG", nullable=True)
    y2017_usd: Mapped[Optional[float]] = mapped_column(Float, name="2017_USD", nullable=True)
    y2018_kg: Mapped[Optional[float]] = mapped_column(Float, name="2018_KG", nullable=True)
    y2018_usd: Mapped[Optional[float]] = mapped_column(Float, name="2018_USD", nullable=True)
    y2019_kg: Mapped[Optional[float]] = mapped_column(Float, name="2019_KG", nullable=True)
    y2019_usd: Mapped[Optional[float]] = mapped_column(Float, name="2019_USD", nullable=True)
    y2020_kg: Mapped[Optional[float]] = mapped_column(Float, name="2020_KG", nullable=True)
    y2020_usd: Mapped[Optional[float]] = mapped_column(Float, name="2020_USD", nullable=True)
    y2021_kg: Mapped[Optional[float]] = mapped_column(Float, name="2021_KG", nullable=True)
    y2021_usd: Mapped[Optional[float]] = mapped_column(Float, name="2021_USD", nullable=True)
    y2022_kg: Mapped[Optional[float]] = mapped_column(Float, name="2022_KG", nullable=True)
    y2022_usd: Mapped[Optional[float]] = mapped_column(Float, name="2022_USD", nullable=True)
    y2023_kg: Mapped[Optional[float]] = mapped_column(Float, name="2023_KG", nullable=True)
    y2023_usd: Mapped[Optional[float]] = mapped_column(Float, name="2023_USD", nullable=True)
    y2024_kg: Mapped[Optional[float]] = mapped_column(Float, name="2024_KG", nullable=True)
    y2024_usd: Mapped[Optional[float]] = mapped_column(Float, name="2024_USD", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


class Exportacao(Base):
    __tablename__ = "stg_exportacao"
    __table_args__ = {"schema": "vitivinicultura"}

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    pais: Mapped[Optional[str]] = mapped_column(String, name="pais", nullable=True)

    # Years 1970-2024, both KG and USD
    y1970_kg: Mapped[Optional[float]] = mapped_column(Float, name="1970_KG", nullable=True)
    y1970_usd: Mapped[Optional[float]] = mapped_column(Float, name="1970_USD", nullable=True)
    y1971_kg: Mapped[Optional[float]] = mapped_column(Float, name="1971_KG", nullable=True)
    y1971_usd: Mapped[Optional[float]] = mapped_column(Float, name="1971_USD", nullable=True)
    y1972_kg: Mapped[Optional[float]] = mapped_column(Float, name="1972_KG", nullable=True)
    y1972_usd: Mapped[Optional[float]] = mapped_column(Float, name="1972_USD", nullable=True)
    y1973_kg: Mapped[Optional[float]] = mapped_column(Float, name="1973_KG", nullable=True)
    y1973_usd: Mapped[Optional[float]] = mapped_column(Float, name="1973_USD", nullable=True)
    y1974_kg: Mapped[Optional[float]] = mapped_column(Float, name="1974_KG", nullable=True)
    y1974_usd: Mapped[Optional[float]] = mapped_column(Float, name="1974_USD", nullable=True)
    y1975_kg: Mapped[Optional[float]] = mapped_column(Float, name="1975_KG", nullable=True)
    y1975_usd: Mapped[Optional[float]] = mapped_column(Float, name="1975_USD", nullable=True)
    y1976_kg: Mapped[Optional[float]] = mapped_column(Float, name="1976_KG", nullable=True)
    y1976_usd: Mapped[Optional[float]] = mapped_column(Float, name="1976_USD", nullable=True)
    y1977_kg: Mapped[Optional[float]] = mapped_column(Float, name="1977_KG", nullable=True)
    y1977_usd: Mapped[Optional[float]] = mapped_column(Float, name="1977_USD", nullable=True)
    y1978_kg: Mapped[Optional[float]] = mapped_column(Float, name="1978_KG", nullable=True)
    y1978_usd: Mapped[Optional[float]] = mapped_column(Float, name="1978_USD", nullable=True)
    y1979_kg: Mapped[Optional[float]] = mapped_column(Float, name="1979_KG", nullable=True)
    y1979_usd: Mapped[Optional[float]] = mapped_column(Float, name="1979_USD", nullable=True)
    y1980_kg: Mapped[Optional[float]] = mapped_column(Float, name="1980_KG", nullable=True)
    y1980_usd: Mapped[Optional[float]] = mapped_column(Float, name="1980_USD", nullable=True)
    y1981_kg: Mapped[Optional[float]] = mapped_column(Float, name="1981_KG", nullable=True)
    y1981_usd: Mapped[Optional[float]] = mapped_column(Float, name="1981_USD", nullable=True)
    y1982_kg: Mapped[Optional[float]] = mapped_column(Float, name="1982_KG", nullable=True)
    y1982_usd: Mapped[Optional[float]] = mapped_column(Float, name="1982_USD", nullable=True)
    y1983_kg: Mapped[Optional[float]] = mapped_column(Float, name="1983_KG", nullable=True)
    y1983_usd: Mapped[Optional[float]] = mapped_column(Float, name="1983_USD", nullable=True)
    y1984_kg: Mapped[Optional[float]] = mapped_column(Float, name="1984_KG", nullable=True)
    y1984_usd: Mapped[Optional[float]] = mapped_column(Float, name="1984_USD", nullable=True)
    y1985_kg: Mapped[Optional[float]] = mapped_column(Float, name="1985_KG", nullable=True)
    y1985_usd: Mapped[Optional[float]] = mapped_column(Float, name="1985_USD", nullable=True)
    y1986_kg: Mapped[Optional[float]] = mapped_column(Float, name="1986_KG", nullable=True)
    y1986_usd: Mapped[Optional[float]] = mapped_column(Float, name="1986_USD", nullable=True)
    y1987_kg: Mapped[Optional[float]] = mapped_column(Float, name="1987_KG", nullable=True)
    y1987_usd: Mapped[Optional[float]] = mapped_column(Float, name="1987_USD", nullable=True)
    y1988_kg: Mapped[Optional[float]] = mapped_column(Float, name="1988_KG", nullable=True)
    y1988_usd: Mapped[Optional[float]] = mapped_column(Float, name="1988_USD", nullable=True)
    y1989_kg: Mapped[Optional[float]] = mapped_column(Float, name="1989_KG", nullable=True)
    y1989_usd: Mapped[Optional[float]] = mapped_column(Float, name="1989_USD", nullable=True)
    y1990_kg: Mapped[Optional[float]] = mapped_column(Float, name="1990_KG", nullable=True)
    y1990_usd: Mapped[Optional[float]] = mapped_column(Float, name="1990_USD", nullable=True)
    y1991_kg: Mapped[Optional[float]] = mapped_column(Float, name="1991_KG", nullable=True)
    y1991_usd: Mapped[Optional[float]] = mapped_column(Float, name="1991_USD", nullable=True)
    y1992_kg: Mapped[Optional[float]] = mapped_column(Float, name="1992_KG", nullable=True)
    y1992_usd: Mapped[Optional[float]] = mapped_column(Float, name="1992_USD", nullable=True)
    y1993_kg: Mapped[Optional[float]] = mapped_column(Float, name="1993_KG", nullable=True)
    y1993_usd: Mapped[Optional[float]] = mapped_column(Float, name="1993_USD", nullable=True)
    y1994_kg: Mapped[Optional[float]] = mapped_column(Float, name="1994_KG", nullable=True)
    y1994_usd: Mapped[Optional[float]] = mapped_column(Float, name="1994_USD", nullable=True)
    y1995_kg: Mapped[Optional[float]] = mapped_column(Float, name="1995_KG", nullable=True)
    y1995_usd: Mapped[Optional[float]] = mapped_column(Float, name="1995_USD", nullable=True)
    y1996_kg: Mapped[Optional[float]] = mapped_column(Float, name="1996_KG", nullable=True)
    y1996_usd: Mapped[Optional[float]] = mapped_column(Float, name="1996_USD", nullable=True)
    y1997_kg: Mapped[Optional[float]] = mapped_column(Float, name="1997_KG", nullable=True)
    y1997_usd: Mapped[Optional[float]] = mapped_column(Float, name="1997_USD", nullable=True)
    y1998_kg: Mapped[Optional[float]] = mapped_column(Float, name="1998_KG", nullable=True)
    y1998_usd: Mapped[Optional[float]] = mapped_column(Float, name="1998_USD", nullable=True)
    y1999_kg: Mapped[Optional[float]] = mapped_column(Float, name="1999_KG", nullable=True)
    y1999_usd: Mapped[Optional[float]] = mapped_column(Float, name="1999_USD", nullable=True)
    y2000_kg: Mapped[Optional[float]] = mapped_column(Float, name="2000_KG", nullable=True)
    y2000_usd: Mapped[Optional[float]] = mapped_column(Float, name="2000_USD", nullable=True)
    y2001_kg: Mapped[Optional[float]] = mapped_column(Float, name="2001_KG", nullable=True)
    y2001_usd: Mapped[Optional[float]] = mapped_column(Float, name="2001_USD", nullable=True)
    y2002_kg: Mapped[Optional[float]] = mapped_column(Float, name="2002_KG", nullable=True)
    y2002_usd: Mapped[Optional[float]] = mapped_column(Float, name="2002_USD", nullable=True)
    y2003_kg: Mapped[Optional[float]] = mapped_column(Float, name="2003_KG", nullable=True)
    y2003_usd: Mapped[Optional[float]] = mapped_column(Float, name="2003_USD", nullable=True)
    y2004_kg: Mapped[Optional[float]] = mapped_column(Float, name="2004_KG", nullable=True)
    y2004_usd: Mapped[Optional[float]] = mapped_column(Float, name="2004_USD", nullable=True)
    y2005_kg: Mapped[Optional[float]] = mapped_column(Float, name="2005_KG", nullable=True)
    y2005_usd: Mapped[Optional[float]] = mapped_column(Float, name="2005_USD", nullable=True)
    y2006_kg: Mapped[Optional[float]] = mapped_column(Float, name="2006_KG", nullable=True)
    y2006_usd: Mapped[Optional[float]] = mapped_column(Float, name="2006_USD", nullable=True)
    y2007_kg: Mapped[Optional[float]] = mapped_column(Float, name="2007_KG", nullable=True)
    y2007_usd: Mapped[Optional[float]] = mapped_column(Float, name="2007_USD", nullable=True)
    y2008_kg: Mapped[Optional[float]] = mapped_column(Float, name="2008_KG", nullable=True)
    y2008_usd: Mapped[Optional[float]] = mapped_column(Float, name="2008_USD", nullable=True)
    y2009_kg: Mapped[Optional[float]] = mapped_column(Float, name="2009_KG", nullable=True)
    y2009_usd: Mapped[Optional[float]] = mapped_column(Float, name="2009_USD", nullable=True)
    y2010_kg: Mapped[Optional[float]] = mapped_column(Float, name="2010_KG", nullable=True)
    y2010_usd: Mapped[Optional[float]] = mapped_column(Float, name="2010_USD", nullable=True)
    y2011_kg: Mapped[Optional[float]] = mapped_column(Float, name="2011_KG", nullable=True)
    y2011_usd: Mapped[Optional[float]] = mapped_column(Float, name="2011_USD", nullable=True)
    y2012_kg: Mapped[Optional[float]] = mapped_column(Float, name="2012_KG", nullable=True)
    y2012_usd: Mapped[Optional[float]] = mapped_column(Float, name="2012_USD", nullable=True)
    y2013_kg: Mapped[Optional[float]] = mapped_column(Float, name="2013_KG", nullable=True)
    y2013_usd: Mapped[Optional[float]] = mapped_column(Float, name="2013_USD", nullable=True)
    y2014_kg: Mapped[Optional[float]] = mapped_column(Float, name="2014_KG", nullable=True)
    y2014_usd: Mapped[Optional[float]] = mapped_column(Float, name="2014_USD", nullable=True)
    y2015_kg: Mapped[Optional[float]] = mapped_column(Float, name="2015_KG", nullable=True)
    y2015_usd: Mapped[Optional[float]] = mapped_column(Float, name="2015_USD", nullable=True)
    y2016_kg: Mapped[Optional[float]] = mapped_column(Float, name="2016_KG", nullable=True)
    y2016_usd: Mapped[Optional[float]] = mapped_column(Float, name="2016_USD", nullable=True)
    y2017_kg: Mapped[Optional[float]] = mapped_column(Float, name="2017_KG", nullable=True)
    y2017_usd: Mapped[Optional[float]] = mapped_column(Float, name="2017_USD", nullable=True)
    y2018_kg: Mapped[Optional[float]] = mapped_column(Float, name="2018_KG", nullable=True)
    y2018_usd: Mapped[Optional[float]] = mapped_column(Float, name="2018_USD", nullable=True)
    y2019_kg: Mapped[Optional[float]] = mapped_column(Float, name="2019_KG", nullable=True)
    y2019_usd: Mapped[Optional[float]] = mapped_column(Float, name="2019_USD", nullable=True)
    y2020_kg: Mapped[Optional[float]] = mapped_column(Float, name="2020_KG", nullable=True)
    y2020_usd: Mapped[Optional[float]] = mapped_column(Float, name="2020_USD", nullable=True)
    y2021_kg: Mapped[Optional[float]] = mapped_column(Float, name="2021_KG", nullable=True)
    y2021_usd: Mapped[Optional[float]] = mapped_column(Float, name="2021_USD", nullable=True)
    y2022_kg: Mapped[Optional[float]] = mapped_column(Float, name="2022_KG", nullable=True)
    y2022_usd: Mapped[Optional[float]] = mapped_column(Float, name="2022_USD", nullable=True)
    y2023_kg: Mapped[Optional[float]] = mapped_column(Float, name="2023_KG", nullable=True)
    y2023_usd: Mapped[Optional[float]] = mapped_column(Float, name="2023_USD", nullable=True)
    y2024_kg: Mapped[Optional[float]] = mapped_column(Float, name="2024_KG", nullable=True)
    y2024_usd: Mapped[Optional[float]] = mapped_column(Float, name="2024_USD", nullable=True)
    tag: Mapped[Optional[str]] = mapped_column(String, name="tag", nullable=True)


def create_tables():
    """Create all tables in the database."""
    engine = connections.get_engine()
    Base.metadata.create_all(engine)
